# Use a ROS Humble base image
FROM ros:humble

# Set the working directory to /ros
WORKDIR /workspace

# Update the package list
RUN apt update

# Install dependencies
RUN apt install -y \
    python3-pip \
    portaudio19-dev \
    libasound2-dev \
    libportaudio2

# Install OpenWakeWord and PyAudio using pip
RUN pip3 install \
    openwakeword==0.5 \
    pyaudio \
    sounddevice

RUN colcon build --symlink-install 