csv_file: 'selected_audios_cml.csv'
output_folder: 'teste_codigo_positivo'
negative_output_folder: 'teste_codigo_negativo'
n_samples_positive: 1000
n_samples_negative: 100
keyword: 'keyword'
random: True